---
- name: Create a instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: ansible-gce-262114
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /home/ku9n/.ansible/tmp/ansible-gce-262114-0246eaeb8ce7.json
      gcp_acc_email: ansible@ansible-gce-262114.iam.gserviceaccount.com
      zone: "europe-west1-b"
      region: "europe-west1"

  tasks:
   - name: create a hd
     gcp_compute_disk:
         name: 'hdfortest'
         size_gb: 10
         source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk
   - name: create a network
     gcp_compute_network:
         name: 'network-instance'
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: network
   - name: create a address
     gcp_compute_address:
         name: 'address-instance'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: address
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: ansibletest
         machine_type: g1-small
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network: "{{ network }}"
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
   - name: SSH
     wait_for: host={{ item.public_ip }} port=22 delay=1 timeout=30 state=started
     with_items: "{{ gce.instance_data }}"
   - name: Add host to groupname
     add_host: hostname={{ item.public_ip }} groupname=new_instances
     with_items: "{{ gce.instance_data }}"
- name: Manage new instances
  hosts: new_instances
  connection: ssh
  sudo: True
  roles:
    - base_configuration
    - production_server
   - name: Allow HTTP traffic
     gce_net:
         fwname: pass-http
         name: default
         allowed: tcp:80
         project: "{{ gcp_project }}"
         service_account_file: "{{ gcp_cred_file }}"
         service_account_email: "{{ gcp_acc_email }}"
   - name: Allow HTTPS traffic
     gce_net:
         fwname: pass-https
         name: default
         allowed: tcp:443
         project: "{{ gcp_project }}"
         service_account_file: "{{ gcp_cred_file }}"
         service_account_email: "{{ gcp_acc_email }}"
