---
- name: Install Jenkins
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Download + key jenkins.repo
      script: /home/ku9n/onlymyproject/ansible/jensetup.sh

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Install transport https
      apt:
        name: apt-transport-https
        state: present

    - name: Sleep for 30 seconds and continue with play
      wait_for: timeout=30

    - name: Get init password Jenkins
      shell: cat /user/share/tomcat/.jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: Print init password Jenkins
      debug:
        var: result.stdout
